version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  phylum: {}

filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  test-deploy:
    jobs:
      - phylum/analyze:
          api_key: ${PHYLUM_API_KEY}
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: phylum-dev/phylum
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - phylum/analyze
          context: orb-publishing
          filters: *release-filters
